fullstorydev/grpcurl

cmd/grpcurl/grpcurl.go
grpcurl.go
grpcurl_test.go
tls_settings_test.go

When the test was written, `grpc.Dial` returned underlying connect error on failure/timeout. Now (sadly) it only returns a context cancelled/timeout error.
Also, go "tip" version issues compile errors for format pattern mistakes and caught a problem with an error message that was using `"%d"` for a string value.
A considerable downside of this is that all connection and TLS exceptions simply get reported as timeouts 😦. I'll also be filing a bug in the GRPC project about this sudden inability to access the cause of connection errors.

grpc connection management no longer yields same errors from dial

---

cmd/grpcurl/grpcurl.go
grpcurl.go
grpcurl_test.go

This protobuf default is really quite confusing:
Example call before:
```
$ echo '{"subjects": ["teams:admins2"], "resource": "authz:nodes:foo:run_list", "action": "nodes:read" }' | grpcurl -v -d @ localhost:9094 authz.Authorization/IsAuthorized
Resolved method descriptor:
{
"name": "IsAuthorized",
"inputType": ".authz.IsAuthorizedReq",
"outputType": ".authz.IsAuthorizedResp",
"options": {
}
}
Request metadata to send:
(empty)
Response headers received:
content-type: application/grpc
Response contents:
{
}
```
This happened because defaults are omitted, but for a boolean response, the `false` case actually is quite interesting! 😄 
So, with this, we'd have grpcurl emit defaults, and the crucial section of the output becomes:
```
Response contents:
{
"authorized": false
}
```
What do you …

make jsonpb marshaler emit defaults

---

grpcurl.go

This allows usage of the root package if you perform your own parsing of Protobuf files into `FileDescriptorSets`.

Add DescriptorSourceFromFileDescriptorSet

---

cmd/grpcurl/grpcurl.go

When invoking an RPC, the output to stdout is valid JSON except for the summary message that is printed. For inter-op with tools like `jq`, we can omit that message and only show it in verbose mode (which prints lots of other non-JSON stuff to stdout).
This fixes #18.

trailing message on invocation should only be printed in verbose mode

---

cmd/grpcurl/grpcurl.go

Sometimes a trusted cert's hostname cannot be identical to the DNS
label. This flag enables to override the hostname on validation, such
that one is not forced to use --insecure.

Override server name when validating TLS cert

---

.travis.yml
Makefile
cmd/grpcurl/grpcurl.go
grpcurl.go
testing/test_server.go

Most of the lint complaints were either the form (1) `if` block has a return statement so remove `else` block and outdent it (2) or function returns error value that is being ignored. For the latter, many of the cases were appropriate to ignore the error, so I just added `_ = ` to "consume" the error and get rid of the lint failures.

enable all linters in CI; fix lint issues

---

Makefile

The `predeclared` check was not actually being run. Now it is.

oops - copy-pasta mistake in Makefile

---

cmd/grpcurl/grpcurl.go

So that you inform reverse proxy servers to use it for routing.
Tested with nginx/1.13.12, which is the latest release of nginx as of today.
Usage: `grpcurl --authority example.com localhost`
See https://github.com/grpc/grpc-go/pull/1064 for the PR to grpc-go which enabled this feature.
See https://tools.ietf.org/html/rfc7540#section-8.1.2.3 and https://tools.ietf.org/html/rfc3986#section-3.2 for what is a valid :authority header value.
Note that `grpcurl -H ':authority: example.com' localhost` doesn't work in two ways.
One is that the current implementation of grpcurl splits `:authority: example.com` to `[]string{"", "authority: example}` and considers it as a header with an empty key and a value of "authority: example.com" which isn't valid.
Another one is that `-H` passes request …

Allow passing :authority pseudo header

---

cmd/grpcurl/grpcurl.go

When describing a service, InputType and OutputType symbols are presented
as .Foo.Bar. However, when describing a type, .Foo.Bar is not accepted;
it must be changed to Foo.Bar. This is both confusing and breaks copy
paste ability. This commit addresses the problem by optionally allowing a
period at the beginning of a symbol.
Fixes #39.

allow period at the start of a symbol

---

.travis.yml

Some of the checkers (`unused` and `staticcheck`) are no longer compatible with Go 1.8 and older. 
Also, if a standard check (`gofmt` for example) changed between Go versions, we wouldn't want a case where the build is red because the repo is correct for the latest version of the tool but marked incorrect by an older version.

only run extra checks for one build (Go 1.10), not all of them

---

README.md

Service reflection has very poor SEO and unfortunately not great discoverability. Since this package is an entry-point for service reflection, this helps make the process of finding this information easier.
Sidenote: I'm excited for the talk on grpcurl at Gophercon, and I think this will help users who investigate the package for the first time after seeing the talk. :)
Sidenote 2: I'm not absolutely sold on plopping in a huge code block right there at the top of the readme. If you prefer this in a different place, let me know,

Point to server reflection docs

---

grpcurl.go

Hi, I love grpcurl.
I found a typo of comments while reading the code.
Would you please merge if there is no problem?

fix typo in InvokeRpc() comment

---

cmd/grpcurl/go1_10.go
cmd/grpcurl/go1_9.go
cmd/grpcurl/grpcurl.go
cmd/grpcurl/indent_test.go
cmd/grpcurl/unix.go

In Go 1.10, flag doc strings get auto-indented if they consist of multiple lines. This is not the case for older versions of Go. So this change makes the `grpcurl` usage output prettier in Go 1.10 (and consistent with older versions).
It also adds a test to verify that flag usage output is right. Finally, it improves the indentation, to make the doc strings easier to read and scan with a glance.

improve flag doc with go 1.10+

---

cmd/grpcurl/formatting_test.go
cmd/grpcurl/grpcurl.go
go.mod
go.sum
grpcurl.go

The output of using the `describe` verb was pretty gross: the JSON format of a descriptor proto. It was very verbose, yet at the same time hard to glean useful info from it.
This change makes it emit proto source instead, which is more concise but also more useful and much easier to read.
Here's an example of the difference. This is the new hotness:
```
> grpcurl -plaintext 127.0.0.1:12345 describe .Bank
Bank is a service:
service Bank {
rpc CloseAccount ( .CloseAccountRequest ) returns ( .google.protobuf.Empty );
rpc Deposit ( .DepositRequest ) returns ( .BalanceResponse );
rpc GetAccounts ( .google.protobuf.Empty ) returns ( .GetAccountsResponse );
rpc GetTransactions ( .GetTransactionsRequest ) returns ( stream .Transaction );
rpc OpenAccount ( .OpenAccountRequest ) returns ( .Account …
```

use proto syntax for describe

---

cmd/grpcurl/grpcurl.go
format.go
format_test.go
grpcurl.go

This is to make updating our internal version of the tool simpler going forward: it moves more common logic from the `main` package to the shared package.
There are no major changes to logic, just moving code around. Most of the changes, aside from just cutting/pasting the code to a different file in another package, are renaming things (including making the symbols exported) and adding Go doc. Other minor changes include adding some parameters and an `error` return value here and there, since the new home for the logic cannot access helper functions and command-line flags that are defined in `main`.
The only change that was not purely move-related and mechanical was in printing the request template (your favorite feature): it now re-uses some shared logic (by calling new …

move more stuff from cmd to package

---

cmd/grpcurl/grpcurl.go
grpcurl.go
grpcurl_test.go

We had fixed this in our internal version of the tool. Now that I've made `MakeTemplate` part of the API in the common package, it warrants receiving the same fix. Without this change, showing a template for a message that either *is* or includes `google.protobuf.Any` or `google.protobuf.Value` blows up, because the "zero value" for those types is incompatible with their canonical JSON format.
The test is also copied from our internal version of the tool.
This makes an incompatible API change to `MakeTemplate`. But since that API was *just* added to the package and has never been part of a release, I think it's okay to change it. At some point, I'll add some verbage to the README that indicates that unreleased APIs should be considered unstable until they are included in a release.

MakeTemplate should be more robust

---

format.go
format_test.go
grpcurl.go

Hopefully addresses #73, where an error occurs trying to resolve the `ServerReflection` service, which isn't even being used!
The code is trying to resolve that service in an attempt to enumerate *all* files that it can download from the server. This is then used to build a registry for parsing `google.protobuf.Any` messages. But this is quite heavy-handed -- not only is it overhead to try to load all files from the server, but they may never be needed if the input requests do not contain any `Any` messages.
This patch makes the loading of files for the `Any` registry best effort -- it will load what it can but basically ignore errors along the way. I've also added a TODO to make this be *not* heavy-handed: a custom `AnyResolver` could be provided that looks up descriptors lazily, as they …

make method invocation resilient to errors trying to load all files from server

---

testing/cmd/testserver/testserver.go

Failed build: https://travis-ci.org/fullstorydev/grpcurl/jobs/474681985
This fixes the issues, both of which are suggestions to use `time.Since` instead of `time.Now().Sub`.

fix minor issues caught by staticcheck

---

invoke.go

The test code was racy: if the server sent back an error code without reading any request messages, it was non-deterministic whether client would be allowed to send requests (in some case, it may not have received server's error code, and allowed the send; but it was also possible for the error to have already been received and the send would then fail).
Previously, the sending goroutine would always cancel the context, but something in gRPC is apparently looking at the context and lets the cancellation take precedence over whatever error code was actually received by the server. This means that some tests expecting to fail with a particular code (e.g. "precondition failed") could instead see a "cancelled" error code, which causes a test assertion to fail.
This fixes it: the context is …

fix flaky test where code can be 'cancelled' unexpectedly

---

cmd/grpcurl/grpcurl.go
cmd/grpcurl/unix.go

Just in case we ever link in a package that litters the default `flag.CommandLine` with its own options (which may not be appropriate to add to `grpcurl`'s CLI options), this changes it to use a custom flag set.
It also includes a revision to the flag doc for `-max-msg-sz` (to improve clarity).

use flagset

---

go.mod
go.sum

A few different JSON-handling bugs will be fixed by this update:
* If a request message included a field of type `google.protobuf.Value` or `google.protobuf.ListValue` and the data that grpcurl wanted to send was a ` "null"` value or `"[]"` empty list (respectively), grpcurl would raise an error, being unable to unmarshal the request data correctly.
* If a response message included a oneof field that was set to its zero/default value, it would not be shown in the response output from grpcurl unless the `-emit-defaults` flag were used.
* If a response message included a oneof field and the `-emit-defaults` flag were used, *all* fields of the oneof would be shown, with the unset fields indicating a zero/default value.
See changes in [v1.2.0 release …

latest protoreflect fixes some bugs in JSON marshaling/unmarshaling

---

desc_source.go

Hi, we updated an exported function comment based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?

Fix function comments based on best practices from Effective Go

---

.travis.yml
Makefile
tls_settings_test.go

Also removes the `-ignore` arg to `staticcheck` invocation and fixes the complaint in code (now that this repo relies on new enough version of grpc-go). And removes the `unused` make target since that tool now reports itself as deprecated and superseded by `staticcheck`.

staticcheck no longer runs on Go 1.10

---

format.go

The `grpcui` repo links in this package, since it also does dynamic RPC. For proper handling of Any messages (including error details), it really wants to use the same `AnyResolver` implementations that this package uses. So this API would make that possible (w/out copy+pasta of the code).

add API to expose AnyResolver implementations backed by a DescriptorSource

---

go.mod
go.sum

This pulls in a bug fix to `protoparse.ResolveFilenames`.
Resolves #108

use protoreflect 1.4.4

---

.gitignore
Dockerfile
Makefile
cmd/grpcurl/grpcurl.go

I tried to craft this so the resulting image is as small as possible. At the same time, trying to adhere to best practices and also make the thing as useful as possible, it does not run as a privileged user in the container and also uses the latest root certs from alpine (so that TLS connections work as long as the site's cert is a typical issuer).
I tested using these commands:
```bash
make docker
docker run fullstorydev/grpcurl:v1.3.0-1-g80b118f --help
docker run fullstorydev/grpcurl:v1.3.0-1-g80b118f api.grpc.me:443 list
```
Assuming this looks good, my plan was to use it to push a v1.3.0 image to Docker Hub and to also add a `docker push` command to the `make release` target at some point.

add official Dockerfile

---

cmd/grpcurl/grpcurl.go
grpcurl.go
grpcurl_test.go

See discussion of the feature here:
https://github.com/fullstorydev/grpcurl/issues/116

Add Expand Headers Feature

---

cmd/grpcurl/grpcurl.go

Hello, we have a server that sends gzip compressed responses for certain RPCs. We were getting the following error:
ERROR:
Code: Unimplemented
Message: grpc: Decompressor is not installed for grpc-encoding "gzip"
This PR adds the import to register the gzip compressor. Our RPCs work as expected with this included.

Register gzip decoder

---

.travis.yml
grpcurl.go

Along with the version bump in https://github.com/fullstorydev/grpcurl/pull/136, this will activate xDSv2 support in [`grpcurl`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api).
@jhump Sorry for the barrage of PRs. A release with binaries would be highly appreciated after this PR.
CC @dfawley
**Edit: This change has manually been verified against an xDS server.**

Activate xDS support in grpcurl

---

releasing/README.md
releasing/RELEASE_NOTES.md
releasing/do-release.sh

I just made a v1.5.0 release that went about as poorly as it could go. The artifacts built by `goreleaser` and published to GitHub were wrong (inadvertently respecting the `GO111MODULE=off` and `GOPATH` environment variable I happened to have set). And the first cut of the Homebrew PR failed CI due to a typo in the version number.
Anyhow, going through all of this again, I've written everything down in a `README.md` file and tried to codify it all in a script.
Ideally, the actual Go build and `goreleaser` invocation steps would use docker images, so they are repeatable and will work regardless of host environment. I didn't get a chance to take it that far yet though.

add script and readme for creating new releases

---

.travis.yml

1.9 and 1.10 are ancient and even App Engine no longer supports them.
1.13 and 1.14 are the new hotness.

drop 1.9 and 1.10; add 1.13 and 1.14

---

.travis.yml

Previously, the vet step was done with modules turned off. This allowed versions of dependencies to be unpinned and pick up newer versions that include newer deprecations. The deprecations made vet unhappy.
This pins the deps during the vet step because we are not at this time intending to move to the new protobuf API (though the old one has now been deprecated). We'll move to the new APIs before too long, but it's a non-trivial amount of work and there are other deps which still use the old API...

vet with modules

---

format.go

This fixes a `str[-1]` dereference if the marshaled text proto is an empty string.
There might be a better way to fix this - maybe `strings.TrimRight(str, "\n")`?

format: fix crash when emitting empty messages in text format

---

format.go

Go tip does not like using `string(i)` where `i` is an untyped int
https://travis-ci.org/github/fullstorydev/grpcurl/jobs/686844524

fix broken build: use a rune literal, not an int literal

---

Dockerfile

With go 1.11, building with modules in a vanilla docker image required installing more junk.
With go1.13, mui simple.

use go 1.13 to build docker image

---

Dockerfile

After thinking about it more, maybe repeatable Docker builds aren't as important as not having to touch the Dockerfile as often to upgrade to newer Go point releases. I personally only ever run `docker build` when doing releases and pushing the images to Docker hub. I'm not sure how many users try to build their own docker file, but presumably, if they don't want the image in Docker hub, then maybe they're not trying to reproduce the exact bits in the release anyway.

unpin Go point release and alpine version in Dockerfile

---

go.mod
go.sum
grpcurl.go

@jhump [Version 1.30.0](https://github.com/grpc/grpc-go/releases/tag/v1.30.0) introduces the new `xds` scheme and some nice improvements to xds in general.

Bump grpc-go to 1.30.0

---

Makefile
cmd/grpcurl/grpcurl.go
go.mod
go.sum
grpcurl.go

My main intent was to move the import of "google.golang.org/grpc/xds" out of the main API package and into the main command package (since it's the command that needs its `init` functions to have run, not the API).
But I ran into an issue testing: some deps kept auto-upgrading when running `make ci`. I realized it was because the make targets were relying on a pre-modules formulation -- using `go get`. But this causes the Go tool to retrieve the latest version, which would then change the version pinned in `go.mod`. So I changed all of these to `GO111MODULE=on go install`, so they just use the version already pinned.
I went ahead and left the deps upgraded though (for `staticcheck` and `predeclared` CI checkers).

move import of xds package to cmd/grpcurl; other go.mod and Makefile tweaks

---

cmd/grpcurl/grpcurl.go
format.go
format_test.go

This PR adds a new option `-allow-unknown-fields` (its default value is `false` so the original behavior does not change) which, if present, will instruct JSON protobuf parser to ignore unknown fields present in the request.
My use case is that I have two services sharing a message. The message got extend with a new field but the services haven't been upgraded yet. The change to the message is backward compatible but I can't use `grpcurl` due to an error: `error getting request data: message type ABC has no known field named my_new_field`.

cmd/grpcurl: add -allow-unknown-fields option

---

.travis.yml

When not running in modules mode, CI `go get`s the latest version of all dependencies. But the [latest grpc module](https://github.com/grpc/grpc-go/pull/3767) (as of like 4 hours ago) no longer supports Go 1.11.
So we can't run CI for Go 1.11 in non-module mode.

no more support for go 1.11 without modules

---

cmd/grpcurl/grpcurl.go

Given value is added to the user-agent header
set by the grpc-go library.
Related: https://github.com/grpc/grpc-go/pull/255

feat: add support for user-agent header

---

cmd/grpcurl/grpcurl.go
invoke.go

Current grpc `status.Status` errors propagated from relection do not respect the `-format-error` flag:
```
$ grpcurl -format-error -H "$EXPIRED_TOKEN" -d '{}' grpc.example.com:8000 method.to.Reflect.Here
Error invoking method "method.to.Reflect.Here": failed to query for service descriptor "method.to.Reflect": rpc error: code = Unauthenticated desc = rpc error: code = Unauthenticated desc = invalid auth token: Token is expired
```
This is due to the error being stringified irrespective of any flags:
https://github.com/fullstorydev/grpcurl/blob/9846afccbc2f34255dfb459dc6f0196a2b6dbe05/invoke.go#L101
---
Propagating the preserved gRPC status error in `gprcurl.InvokeRPC` if `status.FromErrror` is ok correctly produces the expected behaviour when `formatError` is set to true:
```
$ grpcurl …
```

format gRPC status errors when using reflection

---

cmd/grpcurl/grpcurl.go

```diff
- These headers will also be included in reflection requests requests to a server.
+ These headers will also be included in reflection requests to a server.
```

Help text for "-H" option: remove duplicated word

---

go.mod
go.sum

Hi!
We would like to be able to call services using the built in xds resolver:
```
grpcurl ... xds:///myservice ...
```
While this is possible using 1.30.0 ( see #168 ), the newer versions of grpc-go allow you to use [xDS v3 instead of v2](https://github.com/grpc/grpc-go/blob/91d8f0c916d76f2a5aac9e846cd7ffcb838db769/xds/xds.go#L46).
Since the xDS v2 API has been [deprecated](https://www.envoyproxy.io/docs/envoy/latest/api/api_supported_versions) by the Envoy community, it would be nice to have access to v3 in `grpcurl`, so that we eventually can disable the v2 endpoints in the control plane server.
There are of course many other improvements to xDS and grpc-go in this version bump, but this is the primary reason for us to want an update released fairly soon if possible …

Bump grpc-go to 1.37.0

---

go.mod
go.sum

Here are the release notes: https://github.com/jhump/protoreflect/releases/tag/v1.9.0
This brings `grpcurl`'s parsing of proto sources closer to matching the behavior of protoc. It also adds support for custom options for oneof elements in source files (which was previously broken -- so source files that had custom oneof options might not be parseable by grpcurl).

use newer protoreflect

---

cmd/grpcurl/grpcurl.go
grpcurl.go

I was trying to debug an issue with wireshark via:
```
$ grpcurl -vv -cacert gdk/localhost.crt localhost:1337 list
Failed to list services: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: received the unexpected content-type "text/html"
```
Wireshark supports [consuming a key log file](https://wiki.wireshark.org/TLS#Using_the_.28Pre.29-Master-Secret), which is supported by several clients using `SSLKEYLOGFILE`, including:
* [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format)
* Chrome
* [Curl](https://everything.curl.dev/usingcurl/tls/sslkeylogfile)
This patch adds the same capability to grpcurl.
I tested with wireshark and am able to peek inside the TLS packets.

Support SSLKEYLOGFILE environment variable for secrets logging

---

Dockerfile
releasing/do-release.sh

This PR aims at building and pushing multi-arch image on docker hub.
New architectures can be easily added to the platforms to generate manifests for others.

Building multiarch docker image: amd, s390x

---

go.mod
go.sum

issue https://github.com/fullstorydev/grpcurl/issues/278
fix https://github.com/jhump/protoreflect/pull/481

bump github.com/jhump/protoreflect from v1.10.1 to v1.10.2

---

.circleci/config.yml

Since #240, `go.mod` already states that 1.15 is needed to build this repo.
Recent changes to update deps now _require_ 1.15 in order to build and run tests. So this officially removes 1.14 support.

no longer supporting go 1.14

---

go.mod
go.sum

This pulls in a few more fixes relevant to `grpcurl`. Highlights: support for special syntax for `google.protobuf.Any` values in custom options in proto sources when using `-proto` flags and proper robustness when using server reflection with implementations that return multiple/extra data in file responses.

bump protoreflect again, to 1.10.3

---

releasing/do-release.sh

This reverts commit 8ee6c9423b655f2272fb1860040e73b0d198656a.
For the most recent release (v1.8.6), the docker images were built from a Linux VM (instead of from a Macbook Pro, like some earlier releases). Linux ostensibly does not have the same issue with qemu emulating s390x architecture that x86 OS X does, so we can add this back.

Restore support for linux/s390x for the next release.

---

Makefile

Previously on an ancient version, which couldn't support M1 MBPs (darwin/arm64).

use newer goreleaser

---

cmd/grpcurl/unix.go

Enable support for Unix sockets for Windows by enabling "-unix" flag for Windows builds.
This [functionality](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) is available on Windows since the end of 2017.
Closes: https://github.com/fullstorydev/grpcurl/issues/244

[#244] Unix Domain Socket on Windows

---

.goreleaser.yml
releasing/do-release.sh

Needing power(ppc64le) arch based "grpcurl" binaries here https://docs.openshift.com/container-platform/4.9/operators/admin/olm-restricted-networks.html
1. Adding power support for releases and docker images(multi-arch).
signed-off-by : Amit Ghatwal <ghatwala@us.ibm.com>

Adding power(ppc64le) arch support

---

Dockerfile
releasing/README.md
releasing/do-release.sh

Could you push an alpine base image version?
Then you could support more complex commands like this:
```
grpcurl -plaintext \
-H "Authorization: Bearer $$(cat /var/run/secrets/tokens/vault-token)" \
localhost:80 \
example.v1.Service/Func
```
This works with a common auth pattern on kubernetes where auth tokens are mounted into a volume on a pod.
```
apiVersion: v1
kind: Pod
metadata:
name: nginx
spec:
containers:
- image: nginx
name: nginx
volumeMounts:
- mountPath: /var/run/secrets/tokens
name: vault-token
serviceAccountName: build-robot
volumes:
- name: vault-token
projected:
sources:
- serviceAccountToken:
path: vault-token
expirationSeconds: 7200
audience: vault
```

build alpine base image

---

.circleci/config.yml
Dockerfile

https://github.com/fullstorydev/grpcurl/issues/300

Add go 1.18 support; set Dockerfile to go 1.18

---

releasing/README.md
releasing/do-release.sh

I noticed a couple things while going through the release process for v1.8.7.

fixup release process

---

grpcurl_test.go

This is to be merged into #365 so that PR can turn green in CI and be merged.

fix test expectations for latest version of grpc-go

---

invoke.go

This should resolve #394.
The bidi and client streaming methods already had stream accesses behind a `str != nil` check. It was just server-side streaming that was missing these checks :(

Fix nil-dereference panic that can happen invoking a server stream

---

format.go

Fixes the following issue:
> If an error is returned with additional details together with code and message, grpcurl will format it poorly and not show the additional details.

Show additional error details when an rpc fails

---

README.md
cmd/grpcurl/grpcurl.go
grpcurl_test.go

The proper `v1` gRPC reflection has been around for a bit. The "client auto" mechanism still supports falling back to `v1alpha`. Not many support the `v1`, but we should default to it when possible.

Use `grpc.reflection.v1.ServerReflection`

---

.circleci/config.yml
tls_settings_test.go

For the most part, there are no breaking changes.
However, the expired certificate is now showing "expired certificate" although previously it showed a simpler "bad certificate" which was hard-coded into the TLS settings test scenario.
Closes #405.

Run tests on Go 1.21

---

Makefile

This PR disables CGO so we recover the same behaviour we had in v1.8.7, where we don't have any dependencies on C libraries expected to be found in the environment, and was raised in https://github.com/fullstorydev/grpcurl/issues/404#issuecomment-1762593336.
Tested by running `make install` before and after the changes and inspecting the produced binary from a Linux machine (Debian in this case).
**Before**
```sh
ldd $(which grpcurl)
linux-vdso.so.1 (0x00007ffe121e7000)
libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f2346e02000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2346de0000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2346c0c000)
/lib64/ld-linux-x86-64.so.2 (0x00007f2346e26000)
```
**After**
```sh
ldd $(which grpcurl)
not a dynamic …
```

Disable CGO for improved compatibility across distros

---

releasing/README.md
releasing/do-release.sh

During the `bump-formula-pr` step of the release process, which updates the latest version in Homebrew, I hit the following error:
> line 4, col 3: Use /archive/refs/tags URLs for GitHub tarballs (url is https://github.com/fullstorydev/grpcurl/archive/v1.8.9.tar.gz).
Error: 1 problem in 1 formula detected.
I fixed it by manually changing the URL to https://github.com/fullstorydev/grpcurl/archive/refs/tags/v1.8.9.tar.gz.
It's certainly related to this commit from Homebrew: https://github.com/Homebrew/homebrew-core/commit/2fb3971c8235d3d88d328ebaeddaa57a67188d3a
But I don't have more context on why they decided to change it.

Update Tarball URL used by Homebrew

---

cmd/grpcurl/grpcurl.go

I was looking for how to specify a RPC timeout or [deadline](https://grpc.io/docs/guides/deadlines/) via `grpcurl` and tried grepping the `--help` output, but only matched `-connect-timeout`. I found `-max-time` by browsing the codebase looking for `.WithTimeout()` calls. So the motivation of this PR is both to generally clarify the behavior of this flag and also add the words "timeout" and "deadline" specifically to this help text to aid discovery.

Expand the documentation of -max-time to clarify this sets the RPC timeout

---

cmd/grpcurl/grpcurl.go

Shows very basic timing data for the Dial stage (TLS setup and BlockingDial) and InvokeRPC method as well as the total time.

Added initial support for -t flag to show timings

---

.goreleaser.yml
Makefile

Updating the config file to support goreleaser 1.21.0 (the last version which doesn't require go1.21)
At the same time, I'm adding support for building the deb & rpm packages, it would make the install easier on those systems if you don't have to manually move a binary
For the deb/rpm packages, I'm keeping the normal naming schemes (darwin / amd64 / ...). But for the .tar.gz files, I've kept the packages names as they were 
```
~> goreleaser release --snapshot --rm-dist
• starting release...
• loading config file         file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• building...                   commit=334e3f56ded7e1872c141d121dd7f30a877e140f     latest tag=v1.8.9
• pipe skipped                  error=disabled during snapshot mode
• parsing tag …
```

goreleaser: bump version & add nfmp support

---

Dockerfile

https://github.com/fullstorydev/grpcurl/pull/453 updated some version that bumped the minimum required Go version to v1.19, but we forgot to update the Dockerfile, which is still using Go v1.18, and broke the release attempt of gRPCurl v1.9.0.
```
#22 [linux/arm64 builder 6/6] RUN go build -o /grpcurl     -ldflags "-w -extldflags "-static" -X "main.version=$(cat VERSION)""     ./cmd/grpcurl
#22 52.36 # google.golang.org/grpc
#22 52.36 /go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:2182:14: undefined: atomic.Int64
#22 52.36 note: module requires Go 1.19
#22 73.90 # google.golang.org/grpc/balancer/leastrequest
#22 73.90 /go/pkg/mod/google.golang.org/grpc@v1.61.0/balancer/leastrequest/leastrequest.go:83:76: undefined: atomic.Int32
#22 73.90 …
```

Update Dockerfile to use Go v1.21

---

grpcurl.go

gRPC can fetch ServiceConfig by DNS resolver. When ServiceConfig contains health check config, the client should import google.golang.org/grpc/health package to toggle its init() function, which sets the default healthcheck handler function.
Currently, grpcurl doesn't import it, leading service configuration does not take effect, and this MR aims to resolve it.

feat: introduce transparent client side health check

---

.goreleaser.yml

I want to use grpcurl on a raspberry pi 0 and therefore I need 32 bit binaries. As this might be interesting for others, I thought, I could just create a PR for it.

Add 32bit arm build targets

---

README.md
cmd/grpcurl/grpcurl.go
desc_source.go

**Feature Description:**
Add a new option **--proto-out-dir** to grpcurl that allows users to generate .proto files for listed, described, or invoked elements and their transitive dependencies.
**Functionality:**
When using the list and describe verbs, the listed or described elements and their transitive dependencies will be written as .proto files in the specified directory.
**Proposed Implementation:**
Add a new flag:
```go
protoOut = flags.String("proto-out-dir", "", "The name of a directory where the generated .proto files will be written.")
```
**Use Case:**
This feature will be useful for users who need to generate .proto files from gRPC services, especially when working with services that don't have readily available .proto files or when dealing with dynamically generated …

feat: Add functionality to export proto files

---

Makefile

Hoping this tweak will allow https://github.com/fullstorydev/grpcurl/pull/483 to pass after rebase... but I'm not sure.

makefile updates

---

grpcurl.go

This PR removes the custom dialer used by `grpcurl` such that the default `grpc-go` dialer is used. The default `grpc-go` dialer supports proxy configuration similar the `net.http` package (e.g. [ProxyFromEnvironment](https://pkg.go.dev/net/http#ProxyFromEnvironment)).
I'm assuming this is a safe change as all the tests continue to pass and I can now use the `HTTPS_PROXY`  environment variable to route `grpcurl` calls through a proxy. That said, it is not clear to me why a custom dialer was used in the first place, so it is possible I am missing something here. (Based on my reading of the code, the custom dialer doesn't seem to add any additional functionality above and beyond a default `net.Dialer`.)
I have been using `grpcurl` for a couple of years now, but have only recently needed to …

feat: 166: Proxy support

---

.circleci/config.yml
Dockerfile
Makefile

chore: update to Golang 1.23

---

go.mod
go.sum

Updates to fix identified CVEs in stdlib

update core Go version in go.mod

---

.gitignore
README.md
snap/README.md
snap/snapcraft.yaml

Hi!
On top of #512, I am hereby:
- locking down the confinement of the snap to `classic`, this means that the installer has [certain strong guarantees](https://snapcraft.io/docs/snap-confinement) that the package won't do undesired things to their system
- upgrading the grade to `stable`, so that the snap can be released and installed by anyone
- adding a badge to the readme and a note about installing the snap
- a readme so any dev working on this project knows what the snapcraft.yaml is about and how to maintain it
I have released a snap for the current 1.9.3 tag
This means that if you run `sudo snap install grpcurl --channel edge`, you'll have grpcurl 1.9.3 within seconds up and running in your machine!
Which IMHO is great.
The next step, if you're interested, would be to set up some …

Snap: strict confinement, stable grade and docs
