- grpcurl.go
- tls_settings_test.go
Also fleshes out doc for some exported symbols that were previously undocumented.
> support binary headers

- README.md
> fix bad port number in README examples

- cmd/grpcurl/grpcurl.go
- grpcurl.go
- grpcurl_test.go
https://github.com/fullstorydev/grpcurl/issues/11
> Delete references to json.RawMessage

- cmd/grpcurl/grpcurl.go
- cmd/grpcurl/unix.go
- cmd/testserver/testserver.go
- cmd/testserver/unix.go
- grpcurl.go
- tls_settings_test.go
I was looking into #25 and saw that it wasn't very hard to implement. So... I did.
> support unix sockets

- cmd/grpcurl/grpcurl.go
- grpcurl.go
- grpcurl_test.go
This is a feature gap -- a feature provided by similar tools like polyglot and grpc_cli. It was also easy to add since the protoreflect library already supports parsing protos.
> allow the use of proto source files directly, instead of having to compile to protoset files

- grpcurl.go
Strangely, this race condition was tickled by the change I made to allow use of proto sources (not just compiled protoset decsriptor files). But, after evaluating the problem, it was technically racy for all of the kinds of stubs (protosets, proto sources, and those that used server reflection).
It is possible (especially I'd never seen the issue before) that the problem was actually caused by a recent change in the gRPC library.
The problem was that a goroutine was cancelling the stream context after an error was observed on the stream. There are several paths where gRPC stream operations can then use that context error instead of the original stream error. So the test code was expecting a "permission denied", but would occasionally instead see "cancelled".
It turns out, cancelling the …
> fix race condition in bidi tests

- .travis.yml
- go.mod
- go.sum
- grpcurl_test.go
- testing/test.proto
- use Go 1.11 (with and without module support) in CI
- add go.mod and go.sum files
> support go modules

- README.md
Revises the sections that talk about descriptor sources, making them more consistent.
Also adds a link to the Gophercon 2018 talk on grpcurl.
> revise README, improve sections on descriptor sources

- README.md
Update README to mention Homebrew installation method.
Closes #52
> add Homebrew installation method

- cmd/grpcurl/grpcurl.go
Also changes other flags to use `flag.Float64`, instead of using `flag.String` and then manually calling `strconv.ParseFloat` (not sure what I was thinking there...).
This fixes #80.
> add -max-msg-sz flag

- go.mod
- go.sum
Includes some fixes/improvements to JSON and text marshaling for dynamic messages which would benefit grpcurl:
https://github.com/jhump/protoreflect/releases/tag/v1.3.0
> use just-released v1.3.0 protoreflect

- cmd/grpcurl/grpcurl.go
- grpcurl.go
This is so that the underlying gRPC library knows whether TLS is in use, so it will use the correct ":scheme" header.
Fixes #129.
> use wrapped TransportCredentials instead of handling handshake in Dialer

- cmd/grpcurl/grpcurl.go
Allows descriptors or proto files to be supplied that are used as an
additional descriptor source when server reflection is used. This is
needed to resolve message types, embedded in an Any message, that the
server has no knowledge of.
Resolves: #135
> Allow extra descriptor sources in reflection mode

- cmd/grpcurl/grpcurl.go
- format.go
- format_test.go
- go.sum
Thank you for the great tool!
I found myself in a need of estimating serialized proto sizes few times.
Seems like a generally useful feature for `-v` mode.
> Print size of the message in very verbose mode

- .goreleaser.yml
> Releasing for ARM64

- README.md
> freshen README, point to 3rd party packages for install

- grpcurl.go
If a caller of `grpc.BlockingDial` wanted the dial operation to keep retrying in the face of non-temporary errors (like "connection refused"), it is not currently possible. Even if they tried to use an explicit `grpc.FailOnNonTempDialError(false)` option, it is silently overridden by the `BlockingDial` function.
This PR fixes that. So the caller can provide an explicit option and override the default behavior of `BlockingDial` with regards to failing fast. This will be used to remedy https://github.com/fullstorydev/grpcui/issues/101.
> allow callers of BlockingDial to override grpc.FailOnNonTempDialError

- .travis.yml
- Dockerfile
- go.mod
Current golang version v1.13 has some Jfrog XRay security issues. So upgrading to latest v1.16.
> Upgrade golang to 1.15 version

- .goreleaser.yml
Looking forward to prebuilt s390x binary in future releases.
> Release binaries for s390x

- go.mod
- go.sum
This includes several fixes for parsing proto source files.
> update to latest protoreflect

- .github/dependabot.yml
Add dependabot configuration to get automated version and security
updates on go.mod and GitHub Actions.
> feat: Add dependabot configuration

- cmd/grpcurl/grpcurl.go
> Use localhost for default unix domain socket authority

- cmd/grpcurl/grpcurl.go
`grpcui` will need the same treatment.
> Avoid overflow in various timeouts
